### ISSUE TITLE
Debian: "Shared folders" doesn't restart the NFS related services when updating shares

### ISSUE THREAD

**Issue by marcosx86** [mate-desktop-legacy-archive/mate-system-tools#22] opened 2013-12-21 22:16 UTC
When you make any changes to the share's list, it doesn't restart the nfs-kernel-server service, so, the changes will never apply.

**Comment by stefano-k** [comment] 2014-02-27 13:13
Duplicate of #21

**Closed as completed by stefano-k** 2014-02-27 13:13 UTC
Labels: unconfirmed
